const fieldsData = [
  {
    fieldId: "8eofvevervoe",
    name: "P5",
    fieldNumber: 567,
    area: "10ha",
    details: "GPS: N50 E22",
    planter: "FGH 145W",
    owner: "Jan Kowalski",
  },
  {
    fieldId: "8eofvfverveevervoe",
    name: "P2",
    fieldNumber: 345,
    area: "100 ha",
    details: `GPS: N51° 5' 27.2632", E20° 1' 28.0966"`,
    planter: "FGH 145W",
    owner: "Jan Kowalki",
  },
  {
    fieldId: "8eofvfevervoe",
    name: "P112",
    fieldNumber: 123,
    area: "10ha",
    details: "GPS: N50 E22",
    planter: "GDH 156/23",
    owner: "Tomasz Nowak",
  },
  {
    fieldId: "8eodsgsfvfverveevervoe",
    name: "P5",
    fieldNumber: 567,
    area: "10ha",
    details: "GPS: N50 E22",
    planter: "FGH 145W",
    owner: "Jan Kowalki",
  },
  {
    fieldId: "8eofvfv676erveevervoe",
    name: "P5",
    fieldNumber: 567,
    area: "10ha",
    details: "GPS: N50 E22",
    planter: "FGH 145W",
    owner: "Jan Kowalki",
  },
  {
    fieldId: "8eofvfvervdsfvdeevervoe",
    name: "P5",
    fieldNumber: 567,
    area: "10ha",
    details: "GPS: N50 E22",
    planter: "FGH 145W",
    owner: "Jan Kowalki",
  },
  {
    fieldId: "8eofvfverveeverfdfvvoe",
    name: "P5",
    fieldNumber: 567,
    area: "10ha",
    details: "GPS: N50 E22",
    planter: "FGH 145W",
    owner: "Jan Kowalki",
  },
];

module.exports = fieldsData;
